version: '3'
networks:
  neuland:
services:
  thoregon:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env_container
    volumes:
      # map static (file) resources, includes location for uploaded images
      - /home/${USER}/containers/${CONTAINER_NAME}/${CONTAINER_NAME}/www:/thoregon/www
      # map DB folder
      - /home/${USER}/containers/${CONTAINER_NAME}/${CONTAINER_NAME}/data:/thoregon/data
      # map cache folder
      - /home/${USER}/containers/${CONTAINER_NAME}/${CONTAINER_NAME}/.thoregon:/thoregon/.thoregon
      # map config files
      - /home/${USER}/containers/${CONTAINER_NAME}/${CONTAINER_NAME}/etc:/thoregon/etc
    networks:
      - neuland
    ports:
      - ${CONTAINER_PORT}:7777
